apiVersion: 1

datasources:
  - name: InfluxDB_v2_K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: k6org
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
